entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: "/etc/traefik/static-config.yml"
    watch: true

api:
  insecure: true  # Оставляем включенным, чтобы проверить Dashboard

log:
  level: INFO  # Логирование на уровне INFO

accessLog:  # Включает логи доступа
  filePath: "/var/log/traefik/access.log"
  format: json

tracing:
  otlp:
    grpc:
      endpoint: "otel-collector:4317"
      insecure: true
